# Generated by Django 5.0.1 on 2024-07-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_shirt_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default=None, max_length=1, null=True),
        ),
    ]
